# Generated by Django 3.2.3 on 2021-05-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodelsapp', '0003_alter_grade_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_graduation',
            field=models.DateField(),
        ),
    ]
